// AssemblyaiTests.swift
// Auto-generated by swift-openapi-bootstrapper

import Testing
import Assemblyai
import UsefulThings

struct AssemblyaiTests {
    // let client = {
    //         let envFileUrl = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent().appendingPathComponent(".env")
    //         return try! createClient(apiKey: getEnvironmentVariable("API_KEY", from: envFileUrl)!)
    // }()

    @Test func example() async throws {
        // let response = try await client.<#method#>(
        //
        // )
    }
}
