// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// Generate temporary streaming token
    ///
    /// Generates a temporary authentication token for use with streaming services.
    ///
    ///
    /// - Remark: HTTP `GET /v3/token`.
    /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)`.
    func generateStreamingToken(_ input: Operations.generateStreamingToken.Input) async throws -> Operations.generateStreamingToken.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// Generate temporary streaming token
    ///
    /// Generates a temporary authentication token for use with streaming services.
    ///
    ///
    /// - Remark: HTTP `GET /v3/token`.
    /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)`.
    public func generateStreamingToken(
        query: Operations.generateStreamingToken.Input.Query = .init(),
        headers: Operations.generateStreamingToken.Input.Headers = .init()
    ) async throws -> Operations.generateStreamingToken.Output {
        try await generateStreamingToken(Operations.generateStreamingToken.Input(
            query: query,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    /// Production server
    public enum Server1 {
        /// Production server
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "https://streaming.assemblyai.com",
                variables: []
            )
        }
    }
    /// Production server
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://streaming.assemblyai.com",
            variables: []
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
public enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/Error`.
        public struct _Error: Codable, Hashable, Sendable {
            /// Error message describing what went wrong
            ///
            /// - Remark: Generated from `#/components/schemas/Error/error`.
            public var error: Swift.String
            /// Error code for programmatic handling
            ///
            /// - Remark: Generated from `#/components/schemas/Error/code`.
            public var code: Swift.String?
            /// Additional error details if available
            ///
            /// - Remark: Generated from `#/components/schemas/Error/details`.
            public var details: OpenAPIRuntime.OpenAPIObjectContainer?
            /// Creates a new `_Error`.
            ///
            /// - Parameters:
            ///   - error: Error message describing what went wrong
            ///   - code: Error code for programmatic handling
            ///   - details: Additional error details if available
            public init(
                error: Swift.String,
                code: Swift.String? = nil,
                details: OpenAPIRuntime.OpenAPIObjectContainer? = nil
            ) {
                self.error = error
                self.code = code
                self.details = details
            }
            public enum CodingKeys: String, CodingKey {
                case error
                case code
                case details
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    public enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    public enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// Generate temporary streaming token
    ///
    /// Generates a temporary authentication token for use with streaming services.
    ///
    ///
    /// - Remark: HTTP `GET /v3/token`.
    /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)`.
    public enum generateStreamingToken {
        public static let id: Swift.String = "generateStreamingToken"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v3/token/GET/query`.
            public struct Query: Sendable, Hashable {
                /// The desired expiration time for the token in seconds.
                ///
                ///
                /// - Remark: Generated from `#/paths/v3/token/GET/query/expires_in_seconds`.
                public var expires_in_seconds: Swift.Int?
                /// The desired maximum duration for the session started using this token in seconds.
                ///
                ///
                /// - Remark: Generated from `#/paths/v3/token/GET/query/max_session_duration_seconds`.
                public var max_session_duration_seconds: Swift.Int?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - expires_in_seconds: The desired expiration time for the token in seconds.
                ///   - max_session_duration_seconds: The desired maximum duration for the session started using this token in seconds.
                public init(
                    expires_in_seconds: Swift.Int? = nil,
                    max_session_duration_seconds: Swift.Int? = nil
                ) {
                    self.expires_in_seconds = expires_in_seconds
                    self.max_session_duration_seconds = max_session_duration_seconds
                }
            }
            public var query: Operations.generateStreamingToken.Input.Query
            /// - Remark: Generated from `#/paths/v3/token/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.generateStreamingToken.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.generateStreamingToken.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.generateStreamingToken.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - headers:
            public init(
                query: Operations.generateStreamingToken.Input.Query = .init(),
                headers: Operations.generateStreamingToken.Input.Headers = .init()
            ) {
                self.query = query
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v3/token/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v3/token/GET/responses/200/content/json`.
                    public struct jsonPayload: Codable, Hashable, Sendable {
                        /// The temporary authentication token
                        ///
                        /// - Remark: Generated from `#/paths/v3/token/GET/responses/200/content/json/token`.
                        public var token: Swift.String
                        /// The actual expiration time of the token in seconds.
                        ///
                        ///
                        /// - Remark: Generated from `#/paths/v3/token/GET/responses/200/content/json/expires_in_seconds`.
                        public var expires_in_seconds: Swift.Int
                        /// Creates a new `jsonPayload`.
                        ///
                        /// - Parameters:
                        ///   - token: The temporary authentication token
                        ///   - expires_in_seconds: The actual expiration time of the token in seconds.
                        public init(
                            token: Swift.String,
                            expires_in_seconds: Swift.Int
                        ) {
                            self.token = token
                            self.expires_in_seconds = expires_in_seconds
                        }
                        public enum CodingKeys: String, CodingKey {
                            case token
                            case expires_in_seconds
                        }
                    }
                    /// - Remark: Generated from `#/paths/v3/token/GET/responses/200/content/application\/json`.
                    case json(Operations.generateStreamingToken.Output.Ok.Body.jsonPayload)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Operations.generateStreamingToken.Output.Ok.Body.jsonPayload {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.generateStreamingToken.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.generateStreamingToken.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successfully generated temporary token
            ///
            /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.generateStreamingToken.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.generateStreamingToken.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct Unauthorized: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v3/token/GET/responses/401/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v3/token/GET/responses/401/content/application\/json`.
                    case json(Components.Schemas._Error)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas._Error {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.generateStreamingToken.Output.Unauthorized.Body
                /// Creates a new `Unauthorized`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.generateStreamingToken.Output.Unauthorized.Body) {
                    self.body = body
                }
            }
            /// Unauthorized - Invalid or missing API key
            ///
            /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Operations.generateStreamingToken.Output.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            public var unauthorized: Operations.generateStreamingToken.Output.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            public struct BadRequest: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v3/token/GET/responses/400/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v3/token/GET/responses/400/content/application\/json`.
                    case json(Components.Schemas._Error)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas._Error {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.generateStreamingToken.Output.BadRequest.Body
                /// Creates a new `BadRequest`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.generateStreamingToken.Output.BadRequest.Body) {
                    self.body = body
                }
            }
            /// Bad Request - Invalid parameters
            ///
            /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)/responses/400`.
            ///
            /// HTTP response code: `400 badRequest`.
            case badRequest(Operations.generateStreamingToken.Output.BadRequest)
            /// The associated value of the enum case if `self` is `.badRequest`.
            ///
            /// - Throws: An error if `self` is not `.badRequest`.
            /// - SeeAlso: `.badRequest`.
            public var badRequest: Operations.generateStreamingToken.Output.BadRequest {
                get throws {
                    switch self {
                    case let .badRequest(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "badRequest",
                            response: self
                        )
                    }
                }
            }
            public struct TooManyRequests: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v3/token/GET/responses/429/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v3/token/GET/responses/429/content/application\/json`.
                    case json(Components.Schemas._Error)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas._Error {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.generateStreamingToken.Output.TooManyRequests.Body
                /// Creates a new `TooManyRequests`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.generateStreamingToken.Output.TooManyRequests.Body) {
                    self.body = body
                }
            }
            /// Too Many Requests - Rate limit exceeded
            ///
            /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)/responses/429`.
            ///
            /// HTTP response code: `429 tooManyRequests`.
            case tooManyRequests(Operations.generateStreamingToken.Output.TooManyRequests)
            /// The associated value of the enum case if `self` is `.tooManyRequests`.
            ///
            /// - Throws: An error if `self` is not `.tooManyRequests`.
            /// - SeeAlso: `.tooManyRequests`.
            public var tooManyRequests: Operations.generateStreamingToken.Output.TooManyRequests {
                get throws {
                    switch self {
                    case let .tooManyRequests(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "tooManyRequests",
                            response: self
                        )
                    }
                }
            }
            public struct InternalServerError: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v3/token/GET/responses/500/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v3/token/GET/responses/500/content/application\/json`.
                    case json(Components.Schemas._Error)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas._Error {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.generateStreamingToken.Output.InternalServerError.Body
                /// Creates a new `InternalServerError`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.generateStreamingToken.Output.InternalServerError.Body) {
                    self.body = body
                }
            }
            /// Internal Server Error
            ///
            /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)/responses/500`.
            ///
            /// HTTP response code: `500 internalServerError`.
            case internalServerError(Operations.generateStreamingToken.Output.InternalServerError)
            /// The associated value of the enum case if `self` is `.internalServerError`.
            ///
            /// - Throws: An error if `self` is not `.internalServerError`.
            /// - SeeAlso: `.internalServerError`.
            public var internalServerError: Operations.generateStreamingToken.Output.InternalServerError {
                get throws {
                    switch self {
                    case let .internalServerError(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "internalServerError",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
