// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// Generate temporary streaming token
    ///
    /// Generates a temporary authentication token for use with streaming services.
    ///
    ///
    /// - Remark: HTTP `GET /v3/token`.
    /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)`.
    func generateStreamingToken(_ input: Operations.generateStreamingToken.Input) async throws -> Operations.generateStreamingToken.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// Generate temporary streaming token
    ///
    /// Generates a temporary authentication token for use with streaming services.
    ///
    ///
    /// - Remark: HTTP `GET /v3/token`.
    /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)`.
    public func generateStreamingToken(
        query: Operations.generateStreamingToken.Input.Query = .init(),
        headers: Operations.generateStreamingToken.Input.Headers = .init()
    ) async throws -> Operations.generateStreamingToken.Output {
        try await generateStreamingToken(Operations.generateStreamingToken.Input(
            query: query,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    /// Production server
    public enum Server1 {
        /// Production server
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "https://streaming.assemblyai.com",
                variables: []
            )
        }
    }
    /// Production server
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://streaming.assemblyai.com",
            variables: []
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
public enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// - Remark: Generated from `#/components/schemas/Error`.
        public struct _Error: Codable, Hashable, Sendable {
            /// Error message describing what went wrong
            ///
            /// - Remark: Generated from `#/components/schemas/Error/error`.
            public var error: Swift.String
            /// Error code for programmatic handling
            ///
            /// - Remark: Generated from `#/components/schemas/Error/code`.
            public var code: Swift.String?
            /// Additional error details if available
            ///
            /// - Remark: Generated from `#/components/schemas/Error/details`.
            public var details: OpenAPIRuntime.OpenAPIObjectContainer?
            /// Creates a new `_Error`.
            ///
            /// - Parameters:
            ///   - error: Error message describing what went wrong
            ///   - code: Error code for programmatic handling
            ///   - details: Additional error details if available
            public init(
                error: Swift.String,
                code: Swift.String? = nil,
                details: OpenAPIRuntime.OpenAPIObjectContainer? = nil
            ) {
                self.error = error
                self.code = code
                self.details = details
            }
            public enum CodingKeys: String, CodingKey {
                case error
                case code
                case details
            }
        }
        /// Client sends audio data as a base64-encoded string within a JSON object.
        ///
        /// - Remark: Generated from `#/components/schemas/AudioChunk`.
        public typealias AudioChunk = OpenAPIRuntime.Base64EncodedData
        /// - Remark: Generated from `#/components/schemas/UpdateConfigurationPayload`.
        public struct UpdateConfigurationPayload: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/UpdateConfigurationPayload/type`.
            public var _type: Swift.String
            /// Confidence threshold (0-1) for detecting end of turn.
            ///
            /// - Remark: Generated from `#/components/schemas/UpdateConfigurationPayload/end_of_turn_confidence_threshold`.
            public var end_of_turn_confidence_threshold: Swift.Float?
            /// Minimum silence duration in ms when confident about end of turn.
            ///
            /// - Remark: Generated from `#/components/schemas/UpdateConfigurationPayload/min_end_of_turn_silence_when_confident`.
            public var min_end_of_turn_silence_when_confident: Swift.Int?
            /// The maximum amount of silence allowed in a turn before end of turn is triggered.
            ///
            /// - Remark: Generated from `#/components/schemas/UpdateConfigurationPayload/max_turn_silence`.
            public var max_turn_silence: Swift.Int?
            /// Creates a new `UpdateConfigurationPayload`.
            ///
            /// - Parameters:
            ///   - _type:
            ///   - end_of_turn_confidence_threshold: Confidence threshold (0-1) for detecting end of turn.
            ///   - min_end_of_turn_silence_when_confident: Minimum silence duration in ms when confident about end of turn.
            ///   - max_turn_silence: The maximum amount of silence allowed in a turn before end of turn is triggered.
            public init(
                _type: Swift.String,
                end_of_turn_confidence_threshold: Swift.Float? = nil,
                min_end_of_turn_silence_when_confident: Swift.Int? = nil,
                max_turn_silence: Swift.Int? = nil
            ) {
                self._type = _type
                self.end_of_turn_confidence_threshold = end_of_turn_confidence_threshold
                self.min_end_of_turn_silence_when_confident = min_end_of_turn_silence_when_confident
                self.max_turn_silence = max_turn_silence
            }
            public enum CodingKeys: String, CodingKey {
                case _type = "type"
                case end_of_turn_confidence_threshold
                case min_end_of_turn_silence_when_confident
                case max_turn_silence
            }
        }
        /// - Remark: Generated from `#/components/schemas/ForceEndpointPayload`.
        public struct ForceEndpointPayload: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ForceEndpointPayload/type`.
            public var _type: Swift.String
            /// Creates a new `ForceEndpointPayload`.
            ///
            /// - Parameters:
            ///   - _type:
            public init(_type: Swift.String) {
                self._type = _type
            }
            public enum CodingKeys: String, CodingKey {
                case _type = "type"
            }
        }
        /// - Remark: Generated from `#/components/schemas/SessionTerminationPayload`.
        public struct SessionTerminationPayload: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/SessionTerminationPayload/type`.
            public var _type: Swift.String
            /// Creates a new `SessionTerminationPayload`.
            ///
            /// - Parameters:
            ///   - _type:
            public init(_type: Swift.String) {
                self._type = _type
            }
            public enum CodingKeys: String, CodingKey {
                case _type = "type"
            }
        }
        /// - Remark: Generated from `#/components/schemas/SessionBeginsPayload`.
        public struct SessionBeginsPayload: Codable, Hashable, Sendable {
            /// Identifies the type of the message.
            ///
            /// - Remark: Generated from `#/components/schemas/SessionBeginsPayload/type`.
            public var _type: Swift.String
            /// Unique identifier for the streaming session.
            ///
            /// - Remark: Generated from `#/components/schemas/SessionBeginsPayload/id`.
            public var id: Swift.String
            /// ISO 8601 timestamp indicating when the session will expire.
            ///
            /// - Remark: Generated from `#/components/schemas/SessionBeginsPayload/expires_at`.
            public var expires_at: Foundation.Date
            /// Creates a new `SessionBeginsPayload`.
            ///
            /// - Parameters:
            ///   - _type: Identifies the type of the message.
            ///   - id: Unique identifier for the streaming session.
            ///   - expires_at: ISO 8601 timestamp indicating when the session will expire.
            public init(
                _type: Swift.String,
                id: Swift.String,
                expires_at: Foundation.Date
            ) {
                self._type = _type
                self.id = id
                self.expires_at = expires_at
            }
            public enum CodingKeys: String, CodingKey {
                case _type = "type"
                case id
                case expires_at
            }
        }
        /// - Remark: Generated from `#/components/schemas/Word`.
        public struct Word: Codable, Hashable, Sendable {
            /// The transcribed word.
            ///
            /// - Remark: Generated from `#/components/schemas/Word/text`.
            public var text: Swift.String
            /// Start time in milliseconds relative to the beginning of the audio stream.
            ///
            /// - Remark: Generated from `#/components/schemas/Word/start`.
            public var start: Swift.Int
            /// End time in milliseconds relative to the beginning of the audio stream.
            ///
            /// - Remark: Generated from `#/components/schemas/Word/end`.
            public var end: Swift.Int
            /// Confidence score for the word (0.0 to 1.0).
            ///
            /// - Remark: Generated from `#/components/schemas/Word/confidence`.
            public var confidence: Swift.Float
            /// Whether the word is final.
            ///
            /// - Remark: Generated from `#/components/schemas/Word/word_is_final`.
            public var word_is_final: Swift.Bool
            /// Creates a new `Word`.
            ///
            /// - Parameters:
            ///   - text: The transcribed word.
            ///   - start: Start time in milliseconds relative to the beginning of the audio stream.
            ///   - end: End time in milliseconds relative to the beginning of the audio stream.
            ///   - confidence: Confidence score for the word (0.0 to 1.0).
            ///   - word_is_final: Whether the word is final.
            public init(
                text: Swift.String,
                start: Swift.Int,
                end: Swift.Int,
                confidence: Swift.Float,
                word_is_final: Swift.Bool
            ) {
                self.text = text
                self.start = start
                self.end = end
                self.confidence = confidence
                self.word_is_final = word_is_final
            }
            public enum CodingKeys: String, CodingKey {
                case text
                case start
                case end
                case confidence
                case word_is_final
            }
        }
        /// - Remark: Generated from `#/components/schemas/TurnPayload`.
        public struct TurnPayload: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/TurnPayload/type`.
            public var _type: Swift.String
            /// Order of this turn in the conversation.
            ///
            /// - Remark: Generated from `#/components/schemas/TurnPayload/turn_order`.
            public var turn_order: Swift.Int
            /// Whether this turn has been formatted.
            ///
            /// - Remark: Generated from `#/components/schemas/TurnPayload/turn_is_formatted`.
            public var turn_is_formatted: Swift.Bool
            /// Whether this marks the end of a turn.
            ///
            /// - Remark: Generated from `#/components/schemas/TurnPayload/end_of_turn`.
            public var end_of_turn: Swift.Bool
            /// Transcript of all finalized words in the turn.
            ///
            /// - Remark: Generated from `#/components/schemas/TurnPayload/transcript`.
            public var transcript: Swift.String
            /// The confidence score that this is the end of a turn, between 0.0 (low confidence) and 1.0 (high confidence).
            ///
            /// - Remark: Generated from `#/components/schemas/TurnPayload/end_of_turn_confidence`.
            public var end_of_turn_confidence: Swift.Float
            /// Array of word-level details for this turn.
            ///
            /// - Remark: Generated from `#/components/schemas/TurnPayload/words`.
            public var words: [Components.Schemas.Word]
            /// Creates a new `TurnPayload`.
            ///
            /// - Parameters:
            ///   - _type:
            ///   - turn_order: Order of this turn in the conversation.
            ///   - turn_is_formatted: Whether this turn has been formatted.
            ///   - end_of_turn: Whether this marks the end of a turn.
            ///   - transcript: Transcript of all finalized words in the turn.
            ///   - end_of_turn_confidence: The confidence score that this is the end of a turn, between 0.0 (low confidence) and 1.0 (high confidence).
            ///   - words: Array of word-level details for this turn.
            public init(
                _type: Swift.String,
                turn_order: Swift.Int,
                turn_is_formatted: Swift.Bool,
                end_of_turn: Swift.Bool,
                transcript: Swift.String,
                end_of_turn_confidence: Swift.Float,
                words: [Components.Schemas.Word]
            ) {
                self._type = _type
                self.turn_order = turn_order
                self.turn_is_formatted = turn_is_formatted
                self.end_of_turn = end_of_turn
                self.transcript = transcript
                self.end_of_turn_confidence = end_of_turn_confidence
                self.words = words
            }
            public enum CodingKeys: String, CodingKey {
                case _type = "type"
                case turn_order
                case turn_is_formatted
                case end_of_turn
                case transcript
                case end_of_turn_confidence
                case words
            }
        }
        /// - Remark: Generated from `#/components/schemas/TerminationPayload`.
        public struct TerminationPayload: Codable, Hashable, Sendable {
            /// Indicates the session has been terminated.
            ///
            /// - Remark: Generated from `#/components/schemas/TerminationPayload/type`.
            public var _type: Swift.String
            /// Duration of the audio in seconds.
            ///
            /// - Remark: Generated from `#/components/schemas/TerminationPayload/audio_duration_seconds`.
            public var audio_duration_seconds: Swift.Int
            /// Duration of the session in seconds.
            ///
            /// - Remark: Generated from `#/components/schemas/TerminationPayload/session_duration_seconds`.
            public var session_duration_seconds: Swift.Int
            /// Creates a new `TerminationPayload`.
            ///
            /// - Parameters:
            ///   - _type: Indicates the session has been terminated.
            ///   - audio_duration_seconds: Duration of the audio in seconds.
            ///   - session_duration_seconds: Duration of the session in seconds.
            public init(
                _type: Swift.String,
                audio_duration_seconds: Swift.Int,
                session_duration_seconds: Swift.Int
            ) {
                self._type = _type
                self.audio_duration_seconds = audio_duration_seconds
                self.session_duration_seconds = session_duration_seconds
            }
            public enum CodingKeys: String, CodingKey {
                case _type = "type"
                case audio_duration_seconds
                case session_duration_seconds
            }
        }
        /// - Remark: Generated from `#/components/schemas/ReceivePayload`.
        @frozen public enum ReceivePayload: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ReceivePayload/case1`.
            case SessionBeginsPayload(Components.Schemas.SessionBeginsPayload)
            /// - Remark: Generated from `#/components/schemas/ReceivePayload/case2`.
            case TurnPayload(Components.Schemas.TurnPayload)
            /// - Remark: Generated from `#/components/schemas/ReceivePayload/case3`.
            case TerminationPayload(Components.Schemas.TerminationPayload)
            public init(from decoder: any Decoder) throws {
                var errors: [any Error] = []
                do {
                    self = .SessionBeginsPayload(try .init(from: decoder))
                    return
                } catch {
                    errors.append(error)
                }
                do {
                    self = .TurnPayload(try .init(from: decoder))
                    return
                } catch {
                    errors.append(error)
                }
                do {
                    self = .TerminationPayload(try .init(from: decoder))
                    return
                } catch {
                    errors.append(error)
                }
                throw Swift.DecodingError.failedToDecodeOneOfSchema(
                    type: Self.self,
                    codingPath: decoder.codingPath,
                    errors: errors
                )
            }
            public func encode(to encoder: any Encoder) throws {
                switch self {
                case let .SessionBeginsPayload(value):
                    try value.encode(to: encoder)
                case let .TurnPayload(value):
                    try value.encode(to: encoder)
                case let .TerminationPayload(value):
                    try value.encode(to: encoder)
                }
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    public enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    public enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// Generate temporary streaming token
    ///
    /// Generates a temporary authentication token for use with streaming services.
    ///
    ///
    /// - Remark: HTTP `GET /v3/token`.
    /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)`.
    public enum generateStreamingToken {
        public static let id: Swift.String = "generateStreamingToken"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v3/token/GET/query`.
            public struct Query: Sendable, Hashable {
                /// The desired expiration time for the token in seconds.
                ///
                ///
                /// - Remark: Generated from `#/paths/v3/token/GET/query/expires_in_seconds`.
                public var expires_in_seconds: Swift.Int?
                /// The desired maximum duration for the session started using this token in seconds.
                ///
                ///
                /// - Remark: Generated from `#/paths/v3/token/GET/query/max_session_duration_seconds`.
                public var max_session_duration_seconds: Swift.Int?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - expires_in_seconds: The desired expiration time for the token in seconds.
                ///   - max_session_duration_seconds: The desired maximum duration for the session started using this token in seconds.
                public init(
                    expires_in_seconds: Swift.Int? = nil,
                    max_session_duration_seconds: Swift.Int? = nil
                ) {
                    self.expires_in_seconds = expires_in_seconds
                    self.max_session_duration_seconds = max_session_duration_seconds
                }
            }
            public var query: Operations.generateStreamingToken.Input.Query
            /// - Remark: Generated from `#/paths/v3/token/GET/header`.
            public struct Headers: Sendable, Hashable {
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.generateStreamingToken.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - accept:
                public init(accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.generateStreamingToken.AcceptableContentType>] = .defaultValues()) {
                    self.accept = accept
                }
            }
            public var headers: Operations.generateStreamingToken.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - headers:
            public init(
                query: Operations.generateStreamingToken.Input.Query = .init(),
                headers: Operations.generateStreamingToken.Input.Headers = .init()
            ) {
                self.query = query
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v3/token/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v3/token/GET/responses/200/content/json`.
                    public struct jsonPayload: Codable, Hashable, Sendable {
                        /// The temporary authentication token
                        ///
                        /// - Remark: Generated from `#/paths/v3/token/GET/responses/200/content/json/token`.
                        public var token: Swift.String
                        /// The actual expiration time of the token in seconds.
                        ///
                        ///
                        /// - Remark: Generated from `#/paths/v3/token/GET/responses/200/content/json/expires_in_seconds`.
                        public var expires_in_seconds: Swift.Int
                        /// Creates a new `jsonPayload`.
                        ///
                        /// - Parameters:
                        ///   - token: The temporary authentication token
                        ///   - expires_in_seconds: The actual expiration time of the token in seconds.
                        public init(
                            token: Swift.String,
                            expires_in_seconds: Swift.Int
                        ) {
                            self.token = token
                            self.expires_in_seconds = expires_in_seconds
                        }
                        public enum CodingKeys: String, CodingKey {
                            case token
                            case expires_in_seconds
                        }
                    }
                    /// - Remark: Generated from `#/paths/v3/token/GET/responses/200/content/application\/json`.
                    case json(Operations.generateStreamingToken.Output.Ok.Body.jsonPayload)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Operations.generateStreamingToken.Output.Ok.Body.jsonPayload {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.generateStreamingToken.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.generateStreamingToken.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Successfully generated temporary token
            ///
            /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.generateStreamingToken.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.generateStreamingToken.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            public struct Unauthorized: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v3/token/GET/responses/401/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v3/token/GET/responses/401/content/application\/json`.
                    case json(Components.Schemas._Error)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas._Error {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.generateStreamingToken.Output.Unauthorized.Body
                /// Creates a new `Unauthorized`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.generateStreamingToken.Output.Unauthorized.Body) {
                    self.body = body
                }
            }
            /// Unauthorized - Invalid or missing API key
            ///
            /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)/responses/401`.
            ///
            /// HTTP response code: `401 unauthorized`.
            case unauthorized(Operations.generateStreamingToken.Output.Unauthorized)
            /// The associated value of the enum case if `self` is `.unauthorized`.
            ///
            /// - Throws: An error if `self` is not `.unauthorized`.
            /// - SeeAlso: `.unauthorized`.
            public var unauthorized: Operations.generateStreamingToken.Output.Unauthorized {
                get throws {
                    switch self {
                    case let .unauthorized(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "unauthorized",
                            response: self
                        )
                    }
                }
            }
            public struct BadRequest: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v3/token/GET/responses/400/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v3/token/GET/responses/400/content/application\/json`.
                    case json(Components.Schemas._Error)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas._Error {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.generateStreamingToken.Output.BadRequest.Body
                /// Creates a new `BadRequest`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.generateStreamingToken.Output.BadRequest.Body) {
                    self.body = body
                }
            }
            /// Bad Request - Invalid parameters
            ///
            /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)/responses/400`.
            ///
            /// HTTP response code: `400 badRequest`.
            case badRequest(Operations.generateStreamingToken.Output.BadRequest)
            /// The associated value of the enum case if `self` is `.badRequest`.
            ///
            /// - Throws: An error if `self` is not `.badRequest`.
            /// - SeeAlso: `.badRequest`.
            public var badRequest: Operations.generateStreamingToken.Output.BadRequest {
                get throws {
                    switch self {
                    case let .badRequest(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "badRequest",
                            response: self
                        )
                    }
                }
            }
            public struct TooManyRequests: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v3/token/GET/responses/429/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v3/token/GET/responses/429/content/application\/json`.
                    case json(Components.Schemas._Error)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas._Error {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.generateStreamingToken.Output.TooManyRequests.Body
                /// Creates a new `TooManyRequests`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.generateStreamingToken.Output.TooManyRequests.Body) {
                    self.body = body
                }
            }
            /// Too Many Requests - Rate limit exceeded
            ///
            /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)/responses/429`.
            ///
            /// HTTP response code: `429 tooManyRequests`.
            case tooManyRequests(Operations.generateStreamingToken.Output.TooManyRequests)
            /// The associated value of the enum case if `self` is `.tooManyRequests`.
            ///
            /// - Throws: An error if `self` is not `.tooManyRequests`.
            /// - SeeAlso: `.tooManyRequests`.
            public var tooManyRequests: Operations.generateStreamingToken.Output.TooManyRequests {
                get throws {
                    switch self {
                    case let .tooManyRequests(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "tooManyRequests",
                            response: self
                        )
                    }
                }
            }
            public struct InternalServerError: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v3/token/GET/responses/500/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v3/token/GET/responses/500/content/application\/json`.
                    case json(Components.Schemas._Error)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas._Error {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.generateStreamingToken.Output.InternalServerError.Body
                /// Creates a new `InternalServerError`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.generateStreamingToken.Output.InternalServerError.Body) {
                    self.body = body
                }
            }
            /// Internal Server Error
            ///
            /// - Remark: Generated from `#/paths//v3/token/get(generateStreamingToken)/responses/500`.
            ///
            /// HTTP response code: `500 internalServerError`.
            case internalServerError(Operations.generateStreamingToken.Output.InternalServerError)
            /// The associated value of the enum case if `self` is `.internalServerError`.
            ///
            /// - Throws: An error if `self` is not `.internalServerError`.
            /// - SeeAlso: `.internalServerError`.
            public var internalServerError: Operations.generateStreamingToken.Output.InternalServerError {
                get throws {
                    switch self {
                    case let .internalServerError(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "internalServerError",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
